service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:743678946276:table/DataTable

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  insertData:
    handler: src/insertData.handler
    events:
      - httpApi:
          path: /data
          method: post
  getData:
    handler: src/getData.handler
    events:
      - httpApi:
          path: /data
          method: get
  putData:
    handler: src/putData.handler
    events:
      - httpApi:
          path: /data/{id}
          method: put

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DataTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
